//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlabCode.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectMessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlabCode.Common.Resources.ProjectMessageResource", typeof(ProjectMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se eliminaron {0} proyectos.
        /// </summary>
        public static string MensajeEliminarProyecto {
            get {
                return ResourceManager.GetString("MensajeEliminarProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede modificar la fecha de ejecucion porque existen tareas con fechas de
        ///ejecución posteriores a la nueva fecha de finalización.
        /// </summary>
        public static string MensajeFechaEjecucion {
            get {
                return ResourceManager.GetString("MensajeFechaEjecucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proyecto no se encontro o ya se encuentra finalizado.
        /// </summary>
        public static string MensajeProyectFinalizadoNoEncontrado {
            get {
                return ResourceManager.GetString("MensajeProyectFinalizadoNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto actualizado correctamente.
        /// </summary>
        public static string MensajeProyectoActualizado {
            get {
                return ResourceManager.GetString("MensajeProyectoActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proyecto se ha creado exitosamente.
        /// </summary>
        public static string MensajeProyectoCreado {
            get {
                return ResourceManager.GetString("MensajeProyectoCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su proyecto ha finalizado con exito.
        /// </summary>
        public static string MensajeProyectoFinalizado {
            get {
                return ResourceManager.GetString("MensajeProyectoFinalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificación Proyecto Finalizado.
        /// </summary>
        public static string MensajeProyectoFinalizadoTitulo {
            get {
                return ResourceManager.GetString("MensajeProyectoFinalizadoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proyecto no existe.
        /// </summary>
        public static string MensajeProyectoNoExiste {
            get {
                return ResourceManager.GetString("MensajeProyectoNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede completar el proyecto, todavia tiene tareas pendientes por realizar..
        /// </summary>
        public static string MensajeTareasPorRealizar {
            get {
                return ResourceManager.GetString("MensajeTareasPorRealizar", resourceCulture);
            }
        }
    }
}
